<div class="w-full flex items-center mt-6">
    <h3 class="tracking-widest font-semibold text-xl uppercase title-font text-white pb-1 border-b-2 border-indigo-500">
        Accueil
    </h3>
</div>

<div class="w-full mt-4 text-gray-300">
    <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime impedit in ipsam quidem cumque nisi quasi, laborum quas illo porro voluptates accusamus, quisquam ducimus fugit cupiditate praesentium dolor magni, perferendis odio incidunt autem nobis. Assumenda nobis consectetur cum maiores atque veritatis magni iste, minima dolor dicta non voluptate fugiat dignissimos? Error expedita quisquam molestiae, consequuntur qui ut magni, tempora sunt animi eligendi, asperiores quos reprehenderit necessitatibus nam sint voluptatibus ad similique quibusdam aut nulla voluptatum. Facere nesciunt quo hic in eaque excepturi necessitatibus commodi quisquam quam, omnis ab laboriosam at? Animi eveniet tenetur quibusdam, maiores illo saepe officiis, obcaecati vero fuga est incidunt explicabo unde aspernatur. Quod eaque molestias facere error, maiores dolores debitis ipsam illum consequatur eveniet quae amet earum enim quo officia, ullam temporibus cum? Dolores in natus perferendis nam distinctio laborum provident voluptatum eos? Porro reprehenderit nam modi aliquid cum quos dolorum. Repellendus, quidem unde! Voluptatum recusandae exercitationem ipsum molestiae quam est cumque tempora adipisci quia quidem nostrum, rerum necessitatibus consequuntur illum numquam, accusamus alias tempore officiis aliquam! Nobis exercitationem suscipit numquam accusamus nisi cumque consequatur inventore. Nobis impedit, quaerat vel assumenda illo minus veritatis pariatur accusantium quas exercitationem beatae. Ipsa facere dolore, quidem nisi nihil quasi.</p>

    <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta ducimus corrupti, sapiente neque amet quis a cumque ipsum odit in, quaerat vero veritatis molestias natus inventore nihil deserunt magni totam. Quas earum molestiae nemo. Similique inventore excepturi deleniti. Aliquam corporis doloribus quis suscipit ullam esse provident reprehenderit, ipsam quisquam tempora corrupti commodi blanditiis architecto odio temporibus cumque aperiam dolor veritatis delectus et. Sit illum accusantium cumque est dolore sunt obcaecati eos mollitia deleniti corrupti velit modi iste aspernatur, atque natus, nulla voluptas corporis architecto. Laboriosam dolores perferendis dolore possimus necessitatibus magnam suscipit amet sequi commodi officiis ad, quod distinctio voluptatum minima nobis, natus sint, nisi fuga eaque exercitationem ipsa? Qui placeat harum eveniet soluta cupiditate sapiente. Iste illum itaque blanditiis quos debitis praesentium porro error ea reprehenderit accusantium quaerat optio quidem iure distinctio, odio, vero totam vitae in cum dignissimos beatae? Perspiciatis veritatis corrupti quis possimus architecto tempore molestias modi consequuntur, mollitia eum quae libero, sapiente repellendus esse quos est maiores iure repellat aliquid quidem fugit? Cumque repellat nostrum quae alias inventore praesentium, quibusdam fugiat vero ipsum perspiciatis officia magni numquam officiis totam maiores tempora saepe dicta quaerat tenetur amet?</p>

    <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Non blanditiis iure necessitatibus atque dignissimos esse optio eos architecto tempore quis doloremque, consequuntur nostrum? Nemo, laborum quae! Exercitationem tempore, impedit sed dicta optio officiis minima. Cumque est illo voluptatum temporibus, officia iste saepe ab sequi itaque! Enim magnam, ullam aperiam itaque architecto quis natus delectus? Velit necessitatibus iure illum molestiae sed eum ipsum iusto, repellat dolore porro maxime laboriosam quo vero distinctio est sequi natus assumenda? Fugiat, obcaecati! Similique eum odio dolor perferendis a iste libero cupiditate rem corrupti voluptas iure soluta fuga quibusdam quaerat beatae officia molestiae neque, autem saepe. Temporibus mollitia adipisci quam architecto itaque officia veritatis facere velit natus incidunt iste excepturi culpa explicabo optio, soluta, voluptatum voluptatibus deleniti. In, culpa quia quaerat reiciendis odit quo quod error excepturi quidem quisquam laborum modi ratione debitis et ab id numquam libero ex harum eum similique recusandae. Quae at reiciendis doloribus, quibusdam asperiores voluptate optio ipsa saepe officia aperiam accusantium vero. Mollitia accusamus reiciendis saepe iusto cupiditate laudantium adipisci? Laudantium eum nihil delectus sapiente voluptatum laborum nobis. Rem ullam est, minus laboriosam recusandae dolorem delectus quidem iure explicabo nemo omnis, ex dolorum vel aperiam debitis odit, tenetur officia quis culpa? Consectetur, autem minus perspiciatis voluptatibus, nisi distinctio dolor, alias similique quia odio iste quaerat voluptas provident amet? Sapiente nam magni a explicabo suscipit doloribus ipsum, quia, debitis accusantium reiciendis accusamus hic atque cum voluptatum? Accusamus, consequatur nobis unde mollitia itaque voluptate amet, molestiae excepturi aut porro eligendi sequi eius dolore blanditiis esse ullam maxime soluta quis, voluptatum at. Amet, obcaecati.</p>
</div>
